### ISSUE TITLE
un7zip_folder_path contains game folder twice

### ISSUE THREAD

**Issue by nakedpony** [zach-morris/plugin.program.iarl#26]
Thanks for the awesome tool! I really like it.
But we know that all software have some bugs. And here is one that I encounter.

**How to reproduce:**
Clicked download WipeoutXL, then clicked open.

**Versions:**
IARL version: 1.5.9
Libreelec version: 7.95.3 8.0
Kodi version: 17.0 Git:a10c504

Please see log below.
```13:25:46.196 T:1644164000  NOTICE: IARL:  Download and Launch started for 10.  Wipeout XL
13:25:46.273 T:1644164000  NOTICE: IARL:  Download started for 10.  Wipeout XL
13:25:51.768 T:1644164000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: (2, 'No such file or directory', '/storage/.kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/10_Wipeout_XL/10_W
ipeout_XL')
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.program.iarl/addon.py", line 1696, in onClick
                                                download_and_launch_rom(self,iarl_data)
                                              File "/storage/.kodi/addons/plugin.program.iarl/addon.py", line 1481, in download_and_launch_rom
                                                iarl_data['current_save_data'] = download_rom_only(iarl_data)
                                              File "/storage/.kodi/addons/plugin.program.iarl/addon.py", line 1169, in download_rom_only
                                                iarl_data['current_save_data']['launch_filename'], post_download_action_success = post_download_action(iarl_data,iarl_data['curre
nt_archive_data']['emu_post_download_action'],None)
                                              File "/storage/.kodi/addons/plugin.program.iarl/addon.py", line 1373, in post_download_action
                                                conversion_success, converted_filename = convert_7z_m3u(iarl_data)
                                              File "/storage/.kodi/addons/plugin.program.iarl/resources/lib/util.py", line 2452, in convert_7z_m3u
                                                if '.cue' in [os.path.splitext(x)[-1] for x in os.listdir(un7zip_folder_path)]:
                                            OSError: (2, 'No such file or directory', '/storage/.kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/10_Wipeout_XL/10_Wipeout_
XL')
                                            -->End of Python script error report<--
13:25:54.064 T:1962418176   ERROR: GetDirectory - Error getting plugin://plugin.program.iarl/Emulator/PS1_Bestof_ZachMorris/Game/10.++Wipeout+XL
13:25:54.083 T:1962418176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.iarl/Emulator/PS1_Bestof_ZachMorris/Game/10.++Wipeout+XL) failed```

**Comment by zach-morris** [comment]
Thanks.  I'll take a look.  I swear I fixed this issue.

**Comment by zach-morris** [comment]
Should be fixed now, just forgot to copy the fix to this post DL command
