### ISSUE TITLE
NotFoundException: No matching view found for /theme.mp3

### ISSUE THREAD

**Issue by zixelmike** [zach-morris/plugin.program.iarl#74]
Hello! Super plugin! =) All work! But... I`m using kodi 18 and when i opening some item... maybe some NES or Genesis or alse... I see error in kodi "Internet Archive ROM launcher Error" but all open...
Can i do something?
Here my log: 
07:07:22.753 T:140064784578304  NOTICE: IARL:  Lets Play!
07:07:22.842 T:140064784578304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'resources.lib.xbmcswift2b.urls.NotFoundException'>
                                            Error Contents: No matching view found for /theme.mp3
                                            Traceback (most recent call last):
                                              File "/home/zixel/.kodi/addons/plugin.program.iarl/addon.py", line 2365, in <module>
                                                plugin.run()
                                              File "/home/zixel/.kodi/addons/plugin.program.iarl/resources/lib/xbmcswift2b/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/zixel/.kodi/addons/plugin.program.iarl/resources/lib/xbmcswift2b/plugin.py", line 318, in _dispatch
                                                raise NotFoundException, 'No matching view found for %s' % path
                                            NotFoundException: No matching view found for /theme.mp3
                                            -->End of Python script error report<--
07:07:23.375 T:140068576893376   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.program.iarl/theme.mp3]

**Comment by zach-morris** [comment]
I'm assuming you have an addon like TVTunes or something installed, and it's causing the error.  I'm not very familiar with the addon, but it's attempting to play theme.mp3 from the IARL addon path when there is no such file.  You can try disabling the other addon, or somehow configure the other addon to ignore IARL

**Comment by zixelmike** [comment]
Thank you, but I do not understand where the other addon is if the error only occurs in this addon and no theme.mp3 file is present in the whole system =( TvTunes I do not use =( I disable pvr.iptvsimple and i have no errors...=) But i using it... =(

**Comment by zixelmike** [comment]
disable-enable helps! =) but sometimes not))) TY on it)

**Comment by zach-morris** [comment]
I doubt IPTV simple would be causing the issue.  There is some addon in your setup that is trying to play an mp3 from the IARL addon path, so that is at fault.  I will leave this issue open however as I'm updating IARL currently and the issue may act differently with the new version.
